// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvuueehrnqrxxdwnxlix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dXVlZWhybnFyeHhkd254bGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODM4NTUsImV4cCI6MjA3Mjc1OTg1NX0.fXUaYRcj7hmkFNR57beXxhzBDNsBR9VzP4xY3v8ZAeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});